apiVersion: v1
kind: ConfigMap
metadata:
  name: landingpage-pkc-config
data:
  # WebSocket Configuration
  WEBSOCKET_URL: "wss://pkc.pub/ws/"
  
  # Application Configuration
  NODE_ENV: "production"
  PORT: "3000"
